### ISSUE TITLE
Additional calibration method 

### ISSUE THREAD

**Issue by ficematt** [woheller69/Level#44] opened 2024-12-24 17:02 UTC
So one of the ways you can double check a physical level is by rotating it 180 degrees and looking to see if you get the same measurements. 
My thoughts for calibration is store a level measurement, rotate 180 and then calculate back half the change and set zero. This would allow for using phone cases that aren't very flat on the back.

**Comment by woheller69** [comment] 2024-12-24 20:06
Duplicate of #7

**Closed by woheller69** 2024-12-24 20:06 UTC
